---
- name: Copy Hadoop core-site.xml to {{ hadoop_config_path }}
  template:
    src: core-site.xml
    dest: "{{ hadoop_config_path }}"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    mode: "u=rw,g=r,o=r"

- name: Copy Hadoop hdfs-site.xml to {{ hadoop_config_path }}
  template:
    src: hdfs-site.xml
    dest: "{{ hadoop_config_path }}"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    mode: "u=rw,g=r,o=r"

- name: Copy Hadoop mapred-site.xml to {{ hadoop_config_path }}
  template:
    src: mapred-site.xml
    dest: "{{ hadoop_config_path }}"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    mode: "u=rw,g=r,o=r"

- name: Copy Hadoop yarn-site.xml to {{ hadoop_config_path }}
  template:
    src: yarn-site.xml
    dest: "{{ hadoop_config_path }}"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    mode: "u=rw,g=r,o=r"

- name: Copy Hadoop workers to {{ hadoop_config_path }}
  template:
    src: workers
    dest: "{{ hadoop_config_path }}"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    mode: "u=rw,g=r,o=r"

- name: Copy Hadoop Env Script to {{ hadoop_config_path }}
  template:
    src: hadoop-env.sh
    dest: "{{ hadoop_config_path }}"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    mode: "u=rwx,g=rx,o=x"
