---
- include: user.yml
  when: add_user

- name: Create Hadoop Path
  file:
    path: "{{ item }}"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ hadoop_create_path }}"

- include: install.yml
  when: install

- include: config.yml
  when: config

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
