---
- name: Create journalnode edits dir
  file:
    path: "{{ hdfs_dfs_journalnode_edits_dir }}"
    state: directory
    owner: "{{ hdfs_user }}"
    group: "{{ hdfs_group }}"
    mode: "{{ hdfs_dfs_journalnode_edits_dir_perm }}"
  when: '"master" in group_names'

- name: Copy journal service file
  template:
    src: journalnode.ini.j2
    dest: "{{ supervisord_ini_dir }}/journalnode.ini"
    owner: "{{ hdfs_user }}"
    group: "{{ hdfs_group }}"
    mode: "u=rw,g=r,o=r"
  when: '"master" in group_names'
  notify:
    - update supervisord
    - Restart journalnode

- name: Copy zkfc service file {{hdfs_namenodes[0]}}
  template:
    src: zkfc.ini.j2
    dest: "{{ supervisord_ini_dir }}/zkfc.ini"
    owner: "{{ hdfs_user }}"
    group: "{{ hdfs_group }}"
    mode: "u=rw,g=r,o=r"
  when: inventory_hostname == hdfs_namenodes[0]
  notify:
    - update supervisord

- name: Copy zkfc service file {{hdfs_namenodes[1]}}
  template:
    src: zkfc.ini.j2
    dest: "{{ supervisord_ini_dir }}/zkfc.ini"
    owner: "{{ hdfs_user }}"
    group: "{{ hdfs_group }}"
    mode: "u=rw,g=r,o=r"
  when: inventory_hostname == hdfs_namenodes[1]
  notify:
    - update supervisord

- name: Copy namenode service file {{hdfs_namenodes[0]}}
  template:
    src: namenode.ini.j2
    dest: "{{ supervisord_ini_dir }}/namenode.ini"
    owner: "{{ hdfs_user }}"
    group: "{{ hdfs_group }}"
    mode: "u=rw,g=r,o=r"
  when: inventory_hostname == hdfs_namenodes[0]
  notify:
    - update supervisord
    - Restart namenode

- name: Copy namenode service file {{hdfs_namenodes[1]}}
  template:
    src: namenode.ini.j2
    dest: "{{ supervisord_ini_dir }}/namenode.ini"
    owner: "{{ hdfs_user }}"
    group: "{{ hdfs_group }}"
    mode: "u=rw,g=r,o=r"
  when: inventory_hostname == hdfs_namenodes[1]
  notify:
    - update supervisord
    - Restart namenode

- name: Update supervisord
  shell: supervisorctl reread && supervisorctl update
