---
- name: Add Hadoop User {{ hadoop_user }}
  user:
    name: {{ hadoop_user }}
    shell: "/bin/bash"
    append: yes
    home: "{{ hadoop_in"stall_dir }}"
  when: add_user


- name: Check Public Key
  shell: "ls {{ hadoop_install_dir }}/.ssh|grep '.pub' |wc -l"
  register: key_exist
  ignore_errors: true

- name: Generate Public key
  user:
    name: "{{ hadoop_user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  when: "key_exist.stdout == '0' and generate_key"
