---
- name: Add Hadoop User {{ hadoop_user }}
  user:
    name: {{ hadoop_user }}
    shell: "/bin/bash"
    home: "{{ hadoop_install_dir }}"
    append: true

- name: Set authorized key took from file for langerma
  authorized_key:
    user: "{{ hadoop_user }}"
    state: present
    key: '{{ item }}'
  with_file:
    - {{ hadoop_ssh_key }}
