---
- name: Add Hadoop User {{ hadoop_user }}
  user:
    name: "{{ hadoop_user }}"
    shell: "/bin/bash"
    home: "{{ hadoop_install_dir }}"
    append: true

- name: Set authorized key took from file for langerma
  authorized_key:
    user: "{{ hadoop_user }}"
    state: present
    key: "{{ item }}"
  with_file:
    - "{{ hadoop_ssh_key_pub }}"

- name: "copy private key {{ hadoop_ssh_key }} to {{ hadoop_install_dir }}/.ssh/{{ item }}"
  copy:
    src: "{{ hadoop_ssh_key }}"
    dest: "{{ hadoop_install_dir }}/.ssh/id_rsa"
    owner: "{{ hadoop_user }}"
    group: "{{ hadoop_group }}"
    mode: 0600
